apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ml-service-template
  title: 🚀 Deploy ML Service
  description: Create a new ML service with FastAPI + Kubernetes
spec:
  owner: yashaswi
  type: service

  parameters:
    - title: Service Info
      required:
        - name
      properties:
        name:
          type: string
          title: Service Name

  steps:
    - id: fetch
      name: Generate project files
      action: fetch:template
      input:
        url: ./files
        values:
          name: ${{ parameters.name }}

    - id: log
      name: Done
      action: debug:log
      input:
        message: "ML service ${{ parameters.name }} created!"